language: cpp

# reduce clone time by only getting the latest commit and not the whole history (default for travis is 100)
git:
  depth: 1

# only run travis on the master branch
branches:
  only:
    - master
    - Rel19

# build with both gcc and clang to ensure compatibility
compiler:
  - gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libbz2-dev libncurses5-dev libmysqlclient-dev libreadline-dev libsdl1.2-dev libssl-dev zlib1g-dev libace-dev

# Get Eluna
 - git submodule init
 - git submodule update
 
script:
  - test -d _build || mkdir _build
  - test -d _install || mkdir _install
  - cd _build
  - cmake -DCMAKE_INSTALL_PREFIX=../_install ..
  - make -j4
